parser: "@typescript-eslint/parser"
root: true
plugins:
  - "@typescript-eslint"

parserOptions:
  sourceType: module
  project: "./tsconfig.json"
  ecmaFeatures:
    jsx: true
rules:
  semi: [1, always]
  no-extra-semi: error
  "@typescript-eslint/no-unused-vars": error
