parser: "@typescript-eslint/parser"
root: true
plugins:
  - "@typescript-eslint"

parserOptions:
  sourceType: module
  project: "./tsconfig.json"
rules:
  semi: [error, always]
  no-extra-semi: error
  "@typescript-eslint/no-unused-vars": error
